programacion asincrona

js no permite concurrencia


callback funcion definida por nosotros pero que sera ejecutada por otro agente

no se puede capturar valor de retorno
no capturar exceptiocnes

la unica forma es con otro callback


convencion en nodejs pasar el error como primer parametro al cllaback


try {
  console.olg()
  console.log('hola')
} catch(err){
  console.log(err.message)
}
me permite atrapar errores para no bloquear la ejecucion del programa
es un rescue
